export type Payload = {type: string, payload: any};

export const INIT_PROJECTS_DATA_ACTION = "INIT_PROJECTS_DATA";
export const CREATE_PROJECT_ITEM_ACTION = "CREATE_PROJECT_ITEM";
export const FETCH_PROJECTS_DATA_ACTION = "FETCH_PROJECTS_DATA";
export const UPDATE_PROJECT_ITEM_ACTION = "UPDATE_PROJECT_ITEM";
export const DELETE_PROJECT_ITEM_ACTION = "DELETE_PROJECT_ITEM";
